version: 2.1
jobs:
  build:
    docker: 
      - image: node # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: npm i
      - run: npm run e2e