# version: 2.1
# jobs:
#   build:
#     docker: 
#       - image: node # the primary container, where your job's commands are run
#     steps:
#       - checkout # check out the code in the project directory
#       - run: echo "hello world" # run the `echo` command
#       - run: npm i
#       - run: npm run e2e

version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run